import mongoose from "mongoose";

const ProductSchema = new mongoose.Schema(
    {
        name: { type: String, required: true },
        slug: { type: String, required: true, unique: true },
        category: { type: String, required: true, enum: ["onion", "garlic", "blend", "rice", "spice", "frozen"] },
        type: { type: String, required: true },
        description: { type: String, required: true },
        shortDescription: { type: String },
        image: { type: String },
        specifications: {
            meshSize: { type: String },
            moisture: { type: String },
            color: { type: String },
            flavor: { type: String },
            shelfLife: { type: String },
            packaging: { type: String },
            purity: { type: String },
            naturalAdmixture: { type: String },
            averageGrainLength: { type: String },
            elongationUpto: { type: String },
            brokenGrain: { type: String },
            damageDisColorGrain: { type: String },
            immatureGrain: { type: String },
            whiteness: { type: String },
            foreignMatter: { type: String },
            whitenessLight: { type: String },
            whitenessDark: { type: String },
            aroma: { type: String },
            taste: { type: String },
            solubility: { type: String },
            shape: { type: String },
            fryingMedium: { type: String },
            oilContent: { type: String },
            saltContent: { type: String },
            transFat: { type: String },
            saturatedFat: { type: String },
            energy: { type: String },
            protein: { type: String },
            carbohydrates: { type: String },
            sugars: { type: String },
            fat: { type: String },
            sodium: { type: String },
            fiber: { type: String },
        },
        applications: [{ type: String }],
        certifications: [{ type: String }],
        isFeatured: { type: Boolean, default: false },
        isBestSeller: { type: Boolean, default: false },
        minOrderQuantity: { type: String },
        availableForms: [{ type: String }],
    },
    { timestamps: true }
);

export default mongoose.models.Product || mongoose.model("Product", ProductSchema);
